-v ../libs/altera_lnsim.sv
-v ../libs/altera_mf.v
-v ../libs/altera_primitives.v
-v ../libs/220model.v
../tsn_net_build/clk_rst_generate.v
../tsn_net_build/chip_clock_control.v
../tsn_net_build/clk_rst_generate_chip.v
../tsn_net_build/configurable_topology_control.v
../tsn_net_build/read_file_data.v
../tsn_net_build/read_file_ts.v
../tsn_net_build/sync_clock_control.v
../tsn_net_build/sync_control_module.v
../tsn_net_build/top_module.v
../tsn_net_build/top_read_write_file.v
../tsn_net_build/top_read_write_ts.v
../tsn_net_build/ts_clock_control.v
../tsn_net_build/write_file_data.v
../tsn_net_build/write_file_ts.sv
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/fifo/syncfifo_showahead_aclr_w9d256.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/fifo/syncfifo_showahead_aclr_w9d256_fifo_191_53aeptq.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/fifo/syncfifo_showahead_aclr_w35d4.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/fifo/syncfifo_showahead_aclr_w35d4_fifo_191_vo6tksa.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/fifo/syncfifo_showahead_aclr_w64d256.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/fifo/syncfifo_showahead_aclr_w64d256_fifo_191_uadsfsq.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/ram/simpledualportram_drwclock_outputaclr_w8d16.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/ram/simpledualportram_drwclock_outputaclr_w8d16_ram_2port_191_jrxaipq.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/ram/simpledualportram_drwclock_outputaclr_w9d16.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/ram/simpledualportram_drwclock_outputaclr_w9d16_ram_2port_191_lukoefi.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/ram/truedualportram_singleclock_rdenab_outputaclr_w34d4096.v
../tsn_net_build/tsnswitch/ipcore/hardware_control_point/ram/truedualportram_singleclock_rdenab_outputaclr_w34d4096_ram_2port_191_ewxmrhi.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/fifo/fifo_w14d16.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/fifo/fifo_w14d16_fifo_191_7aoiaba.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/fifo/fifo_w61d32.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/fifo/fifo_w61d32_fifo_191_wgu76ka.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/fifo/syncfifo_showahead_aclr_w71d32.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/fifo/syncfifo_showahead_aclr_w71d32_fifo_191_wojwlyy.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/sdprf512x9_s.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/sdprf512x9_s_ram_2port_191_fvxmdzi.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram32x57.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram32x57_ram_2port_191_5cp27sq.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram512x4_rq.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram512x4_rq_ram_2port_191_gytxvfq.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram1024x8_rq.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram1024x8_rq_ram_2port_191_go2l72y.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram16384x9_s.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram16384x9_s_ram_2port_191_emqbfsi.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram65536x134_s.v
../tsn_net_build/tsnswitch/ipcore/time_sensitive_switch/ram/suhddpsram65536x134_s_ram_2port_191_pu2i72y.v
../tsn_net_build/tsnswitch/rtl/tsnswitch.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/hardware_control_point.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/syn_clk_judge.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/cycle_control/cycle_control.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/cycle_control/cycle_start_judge.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/cycle_control/command_parse_and_encapsulate_cc.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/packet_switch/packet_switch.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/packet_switch/pkt_dispatch.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/packet_switch/pkt_select.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/opensync_timing/clock_timing_and_correcting.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/opensync_timing/command_parse_and_encapsulate_ost.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/opensync_timing/local_cnt_timing.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/opensync_timing/opensync_timing.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/address_dispatch.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/hcp_register_group.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/opensync_protocol.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/tsmp_agent.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/tsmp_protocol_process.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/tunnel_frame_process.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/head_and_tail_add/head_and_tail_add.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/head_and_tail_discard/cross_clock_domain_hcp.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/head_and_tail_discard/head_and_tail_discard.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/local_access_control.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_hcp/command_encapsulate_hcp.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_hcp/command_parse_and_encapsulate_hcp.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_hcp/command_parse_hcp.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_inex/command_encapsulate_inex.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_inex/command_parse_and_encapsulate_inex.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_inex/command_parse_inex.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/network_management/ack_type_parse.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/network_management/network_management.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/network_management/network_management_generate.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/network_management/network_management_parse.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/ram_shell/afifo.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/ram_shell/afifo_gray_sync.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/ram_shell/afifo_sync_dff.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/ram_shell/afifo_top.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/ram_shell/ASFIFO_8_16.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/ram_shell/ASFIFO_9_16.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/tsmp_transmit_control/controller_output_schedule.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_agent/tsmp_transmit_control/tsmp_transmit_control.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_forward_table/command_parse_and_encapsulate_tft.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_forward_table/mid_lookup_table.v
../tsn_net_build/tsnswitch/rtl/hardware_control_point/tsmp_forward_table/tsmp_forward_table.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/mbus_parse_and_encapsulate_osm.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_mac.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/packet_statistics.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_receive_pit_record.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_protocol_encapsulate.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_protocol_decapsulate.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_dispatch_pit_compensate.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_1gmac.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/interface_switch_2to1.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/interface_switch_1to2.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/clock_domain_cross.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/mac_process/mac_process.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/mac_process/receive_mac_process.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/mac_process/transmit_mac_process.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_correctionfield_update/opensync_correctionfield_update.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_correctionfield_update/command_parse_and_encapsulate_cfu.v
../tsn_net_build/tsnswitch/rtl/opensync_mac/opensync_1gmac/opensync_correctionfield_update/residence_time_calculate.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/asynfifo_overflow_underflow_output.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/global_registers_management.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/led_on_time.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/opentsn_time_sensitive_switch.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/reset_clock_check.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/reset_glitch.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/reset_sync.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/reset_top.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/signal_sync.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/ram_shell/SFIFO_9_512.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/pkt_centralized_buffer/address_read.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/pkt_centralized_buffer/address_write.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/pkt_centralized_buffer/command_parse_and_encapsulate_pcb.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/pkt_centralized_buffer/pkt_centralized_buffer.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/pkt_centralized_buffer/pkt_read.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/pkt_centralized_buffer/pkt_write.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_output_process.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_output_process_top.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_input_queue/network_input_queue.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_output_schedule/network_output_schedule.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_output_schedule/output_schedule_control.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_output_schedule/virtual_queue_manage.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_queue_manage/network_queue_manage.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_tx/network_tx.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_tx/output_control.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/network_tx/pkt_read_control.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/queue_gate_control/queue_gate_control.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/queue_gate_control/time_slot_calculation.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/queue_gate_control/gate_control.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_output_process/queue_gate_control/command_parse_and_encapsulate_qgc.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/input_buffer_interface.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/network_input_process.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/network_input_process_top.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/frame_filter/command_parse_and_encapsulate_ffi.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/frame_filter/frame_filter.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/frame_filter/frame_transmittion_select.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/frame_filter/head_and_tail_distinguish.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/descriptor_extract/descriptor_extract.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/descriptor_extract/command_parse_and_encapsulate_dex.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/descriptor_extract/data_splice.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/descriptor_extract/descriptor_generate.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/network_input_process/descriptor_extract/descriptor_send.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/mac_self_learning/entry_compare.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/mac_self_learning/mac_self_learning.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/mac_self_learning/mac_self_learning_top.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/mac_self_learning/packet_parse.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/action_selecting.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/command_parse_and_encapsulate_flt.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/descriptor_delay_manage.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/dmac_lookup.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/dmac_tsntag_distinguish.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/flowid_lookup.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/forward_lookup_table.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/standard_packet_action.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/time_division_multiplexing.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/forward_lookup_table/tsn_packet_action.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_output_process.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_tx/control_tx.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_tx/control_read_control.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_tx/control_output_interface.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_queue_management/control_queue_management.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_queue_management/control_input_queue.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/control_output_process/control_queue_management/control_output_queue.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/command_parse_and_encapsulate_tss/command_parse_and_encapsulate_tss.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/command_parse_and_encapsulate_tss/tss_command_parse.v
../tsn_net_build/tsnswitch/rtl/opentsn_time_sensitive_switch/command_parse_and_encapsulate_tss/tss_commandack_generate.v
../tsn_net_build/tsnnic/ip_core/tsnnic/asdprf16x9_rq.v
../tsn_net_build/tsnnic/ip_core/tsnnic/asdprf16x9_rq_ram_2port_150_ay73gla.v
../tsn_net_build/tsnnic/ip_core/tsnnic/asdprf16x8_rq.v
../tsn_net_build/tsnnic/ip_core/tsnnic/asdprf16x8_rq_ram_2port_150_e3awfyy.v
../tsn_net_build/tsnnic/ip_core/tsnnic/sdprf16x22_s.v
../tsn_net_build/tsnnic/ip_core/tsnnic/sdprf16x22_s_ram_2port_191_3eqrjoa.v
../tsn_net_build/tsnnic/ip_core/tsnnic/sdprf32x40_rq.v
../tsn_net_build/tsnnic/ip_core/tsnnic/sdprf32x40_rq_ram_2port_191_udpxaia.v
../tsn_net_build/tsnnic/ip_core/tsnnic/suhddpsram1024x16_rq.v
../tsn_net_build/tsnnic/ip_core/tsnnic/suhddpsram1024x16_rq_ram_2port_191_tdpa2va.v
../tsn_net_build/tsnnic/ip_core/tsnnic/syncfifo_w9d128_aclr_showahead.v
../tsn_net_build/tsnnic/ip_core/tsnnic/syncfifo_w9d128_aclr_showahead_fifo_191_sqyurki.v
../tsn_net_build/tsnnic/ip_core/tsnnic/truedualportram_sclock_outputaclr_w60d32.v
../tsn_net_build/tsnnic/ip_core/tsnnic/truedualportram_sclock_outputaclr_w60d32_ram_2port_191_vw5faqa.v
../tsn_net_build/tsnnic/ip_core/tsnnic/truedualportram_w163d32.v
../tsn_net_build/tsnnic/ip_core/tsnnic/truedualportram_w163d32_ram_2port_191_juicpka.v
../tsn_net_build/tsnnic/ramshell/SFIFO_22_16.v
../tsn_net_build/tsnnic/reset_top_tse.v
../tsn_net_build/tsnnic/rtl/global_registers_management_tse.v
../tsn_net_build/tsnnic/rtl/tennic.v
../tsn_net_build/tsnnic/rtl/time_sensitive_end.v
../tsn_net_build/tsnnic/rtl/command_parse_and_encapsulate_tse/command_parse_and_encapsulate_tse.v
../tsn_net_build/tsnnic/rtl/command_parse_and_encapsulate_tse/tse_command_parse.v
../tsn_net_build/tsnnic/rtl/command_parse_and_encapsulate_tse/tse_commandack_generate.v
../tsn_net_build/tsnnic/rtl/host_input_process/frame_ethtype.v
../tsn_net_build/tsnnic/rtl/host_input_process/host_input_process.v
../tsn_net_build/tsnnic/rtl/host_input_process/tsntag_process.v
../tsn_net_build/tsnnic/rtl/host_input_process/frame_resolution_mapping/command_parse_and_encapsulate_frm.v
../tsn_net_build/tsnnic/rtl/host_input_process/frame_resolution_mapping/frame_resolution_mapping.v
../tsn_net_build/tsnnic/rtl/host_input_process/frame_resolution_mapping/lookup_map_table.v
../tsn_net_build/tsnnic/rtl/host_input_process/frame_resolution_mapping/map_key_extract.v
../tsn_net_build/tsnnic/rtl/host_input_process/frame_resolution_mapping/mapped_frame_outport.v
../tsn_net_build/tsnnic/rtl/host_input_process/interface_state_control/command_parse_and_encapsulate_isc.v
../tsn_net_build/tsnnic/rtl/host_input_process/interface_state_control/interface_state_control.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/ts_injection_management/ts_injection_management.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/ts_injection_schedule/injection_schedule_module.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/ts_injection_schedule/ts_injection_schedule.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/centralized_buffer_interface.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/descriptor_dispatch.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/descriptor_output.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/generate_descriptor.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/pkt_width_transfer.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/time_sensitive_injection_control.v
../tsn_net_build/tsnnic/rtl/host_input_process/time_sensitive_injection_control/time_sensitive_injection_control_cpe.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_output_process.v
../tsn_net_build/tsnnic/rtl/host_output_process/frame_inverse_mapping/command_parse_and_encapsulate_fim.v
../tsn_net_build/tsnnic/rtl/host_output_process/frame_inverse_mapping/frame_inverse_mapping.v
../tsn_net_build/tsnnic/rtl/host_output_process/frame_inverse_mapping/lookup_inversemapping_table.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_queue_management/host_queue_management.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_queue_management/host_output_queue.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_queue_management/host_input_queue.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_tx/host_tx.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_tx/host_read_control.v
../tsn_net_build/tsnnic/rtl/host_output_process/host_tx/host_output_interface.v
../tsn_net_build/tsnnic/rtl/network_input_process/network_input_process_top_tse.v
../tsn_net_build/tsnnic/rtl/network_input_process/network_input_process_tse.v
../tsn_net_build/tsnnic/rtl/network_input_process/descriptor_extract/command_parse_and_encapsulate_dex_tse.v
../tsn_net_build/tsnnic/rtl/network_input_process/descriptor_extract/data_splice_tse.v
../tsn_net_build/tsnnic/rtl/network_input_process/descriptor_extract/descriptor_extract_tse.v
../tsn_net_build/tsnnic/rtl/network_input_process/descriptor_extract/descriptor_generate_tse.v
../tsn_net_build/tsnnic/rtl/network_input_process/descriptor_extract/descriptor_send_tse.v
../tsn_net_build/tsnnic/rtl/network_output_process/descriptor_select/descriptor_select.v
../tsn_net_build/tsnnic/rtl/network_output_process/network_output_process_top_tse.v
../tsn_net_build/tsnnic/rtl/network_output_process/network_output_process_tse.v
../tsn_net_build/tsnnic/rtl/pkt_centralized_buffer/address_read_tse.v
../tsn_net_build/tsnnic/rtl/pkt_centralized_buffer/address_write_tse.v
../tsn_net_build/tsnnic/rtl/pkt_centralized_buffer/command_parse_and_encapsulate_pcb_tse.v
../tsn_net_build/tsnnic/rtl/pkt_centralized_buffer/pkt_centralized_buffer_tse.v
../tsn_net_build/tsnnic/rtl/pkt_centralized_buffer/pkt_read_tse.v
../tsn_net_build/tsnnic/rtl/pkt_centralized_buffer/pkt_write_tse.v
