# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/Dialogwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 140)
        Form.setMinimumSize(QtCore.QSize(420, 140))
        Form.setMaximumSize(QtCore.QSize(420, 140))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TimeLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeLabel.sizePolicy().hasHeightForWidth())
        self.TimeLabel.setSizePolicy(sizePolicy)
        self.TimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TimeLabel.setObjectName("TimeLabel")
        self.horizontalLayout_2.addWidget(self.TimeLabel)
        self.TimeEdit = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimeEdit.sizePolicy().hasHeightForWidth())
        self.TimeEdit.setSizePolicy(sizePolicy)
        self.TimeEdit.setMinimumSize(QtCore.QSize(320, 35))
        self.TimeEdit.setMaximumSize(QtCore.QSize(320, 35))
        self.TimeEdit.setPlaceholderText("")
        self.TimeEdit.setObjectName("TimeEdit")
        self.horizontalLayout_2.addWidget(self.TimeEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ConfirmBut = QtWidgets.QPushButton(Form)
        self.ConfirmBut.setMinimumSize(QtCore.QSize(100, 30))
        self.ConfirmBut.setMaximumSize(QtCore.QSize(100, 30))
        self.ConfirmBut.setObjectName("ConfirmBut")
        self.horizontalLayout_3.addWidget(self.ConfirmBut)
        self.CancelBut = QtWidgets.QPushButton(Form)
        self.CancelBut.setMinimumSize(QtCore.QSize(100, 30))
        self.CancelBut.setMaximumSize(QtCore.QSize(100, 30))
        self.CancelBut.setObjectName("CancelBut")
        self.horizontalLayout_3.addWidget(self.CancelBut)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        self.CancelBut.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Enter the Time"))
        self.TimeLabel.setText(_translate("Form", "Time(ms)"))
        self.ConfirmBut.setText(_translate("Form", "Confirm"))
        self.CancelBut.setText(_translate("Form", "Cancel"))
